apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-project
  template:
    metadata:
      labels:
        app: scan-project
    spec:
      containers:
      - name: scan-project
        image: adegiuli/scan-project-arm32v6
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
        volumeMounts:
        - name: config
          mountPath: /opt/scan/conf
          readOnly: true
        - name: logs
          mountPath: /opt/scan/logs
      volumes:
      - name: config
        configMap:
          name: scan-project
      - name: logs
        nfs:
          server: 192.168.1.18
          path: "/volume1/domosnap-scan"
          
